-- Investment Dashboard schema
-- Applied automatically by the official postgres image on first container start
-- (scripts in /docker-entrypoint-initdb.d run once, in filename order, against
-- the database named by POSTGRES_DB).

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- tickers: canonical list of symbols referenced anywhere in the system
-- ---------------------------------------------------------------------------
CREATE TABLE tickers (
    symbol      TEXT PRIMARY KEY,
    name        TEXT NOT NULL,
    exchange    TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- articles: research articles/briefings. Typically written by the MCP tool
-- (create_article) during the weekly research run, but manual entry is
-- supported too via the REST API.
-- ---------------------------------------------------------------------------
CREATE TABLE articles (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title           TEXT NOT NULL,
    slug            TEXT NOT NULL UNIQUE,
    summary         TEXT,
    body            TEXT NOT NULL,
    conviction      TEXT CHECK (conviction IN ('high', 'medium', 'low')),
    source          TEXT NOT NULL DEFAULT 'mcp' CHECK (source IN ('mcp', 'manual')),
    published_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_articles_published_at ON articles (published_at DESC);

-- ---------------------------------------------------------------------------
-- article_tickers: which tickers a given article discusses, so calendar
-- entries and watchlist items can link back through to the source article.
-- ---------------------------------------------------------------------------
CREATE TABLE article_tickers (
    article_id      UUID NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    ticker_symbol   TEXT NOT NULL REFERENCES tickers(symbol) ON DELETE CASCADE,
    context         TEXT,
    PRIMARY KEY (article_id, ticker_symbol)
);

CREATE INDEX idx_article_tickers_ticker ON article_tickers (ticker_symbol);

-- ---------------------------------------------------------------------------
-- watchlist_items: tickers currently being watched, generated by research
-- articles (or added manually).
-- ---------------------------------------------------------------------------
CREATE TABLE watchlist_items (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticker_symbol       TEXT NOT NULL UNIQUE REFERENCES tickers(symbol) ON DELETE CASCADE,
    conviction          TEXT CHECK (conviction IN ('high', 'medium', 'low')),
    status              TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'removed')),
    notes               TEXT,
    source_article_id   UUID REFERENCES articles(id) ON DELETE SET NULL,
    added_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_watchlist_status ON watchlist_items (status);

-- ---------------------------------------------------------------------------
-- calendar_events: notable dates flagged by research articles (earnings,
-- dividends, macro releases, catalysts, etc.)
-- ---------------------------------------------------------------------------
CREATE TABLE calendar_events (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_date          DATE NOT NULL,
    title               TEXT NOT NULL,
    description         TEXT,
    event_type          TEXT NOT NULL DEFAULT 'other'
                          CHECK (event_type IN ('earnings', 'dividend', 'macro', 'catalyst', 'other')),
    ticker_symbol       TEXT REFERENCES tickers(symbol) ON DELETE CASCADE,
    source_article_id   UUID REFERENCES articles(id) ON DELETE SET NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_calendar_events_date ON calendar_events (event_date);
CREATE INDEX idx_calendar_events_ticker ON calendar_events (ticker_symbol);

-- ---------------------------------------------------------------------------
-- news_items: news headlines related to watch-listed tickers, pulled in by
-- the (currently mocked) news provider.
-- ---------------------------------------------------------------------------
CREATE TABLE news_items (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ticker_symbol   TEXT NOT NULL REFERENCES tickers(symbol) ON DELETE CASCADE,
    headline        TEXT NOT NULL,
    url             TEXT,
    source          TEXT,
    summary         TEXT,
    published_at    TIMESTAMPTZ NOT NULL,
    fetched_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (ticker_symbol, url)
);

CREATE INDEX idx_news_items_ticker ON news_items (ticker_symbol);
CREATE INDEX idx_news_items_published_at ON news_items (published_at DESC);
